name: Terraform Lint

on:
  pull_request:
    paths:
      - '**.tf'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: TFLint Run
        run: tflint --recursive

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
